## catalog of libraries and plugins used to build the KK Physics project

[versions]

jme = "3.6.1-stable"
jolt-java = "0.1.0"

[libraries]

heart = "com.github.stephengold:Heart:9.0.0"
jme3-awt-dialogs = { module = "org.jmonkeyengine:jme3-awt-dialogs", version.ref = "jme" }
jme3-core = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-desktop = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-lwjgl3 = { module = "org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme" }

jolt-java = { module = "com.github.stephengold:jolt-java", version.ref = "jolt-java" }
jolt-java-linux = { module = "com.github.stephengold:jolt-java-natives-linux-x86", version.ref = "jolt-java" }

[bundles]

[plugins]
